networks:
  ocs-network:
    external: true
    name: ocs-net  # The actual network name

services:

  authelia-server:
    image: authelia/authelia
    container_name: authelia-server
    restart: unless-stopped
    user: 1001:1001 # default
    volumes:
      - ./authelia/config:/config:Z
      - ./authelia/secrets:/secrets:Z
    environment:
    - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/JWT_SECRET
    - AUTHELIA_SESSION_SECRET_FILE=/secrets/SESSION_SECRET

  gateway:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx:Z
      - ./certs:/etc/letsencrypt/archive/certs:Z
    ports:
      - 443:443
      - 80:80
    networks:
      - default
      - ocs-network

  whoami:
    container_name: whoami
    image: docker.io/traefik/whoami
    restart: unless-stopped

  lldap:
    container_name: lldap
    hostname: lldap
    image: lldap/lldap:stable
    restart: unless-stopped
    volumes:
      - ./lldap/secrets:/secrets:Z
    environment:
      - UID=0                                              
      - GID=0                                      
      - LLDAP_LDAP_USER_PASS="admin12345"        
      - LLDAP_LDAP_BASE_DN=dc=alphadm,dc=edu
      - LLDAP_JWT_SECRET_FILE=/secrets/JWT_SECRET
      - LLDAP_KEY_SEED=qg3gAOcxCqPlMpk8zCP0LDXxZEiikJ7E84FBbwxPEge6eYuRtpg7VH3bLa6FonBz
      - LLDAP_DATABASE_URL=postgresql://lldap_user:lldap_password@db/general
    ports:
      - 17170:17170

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./db/entrypoint-scripts:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=general
      - LANG=C.UTF-8
    ports:
      - 5432:5432
    logging:
      options:
        max-file: "7"
        max-size: "5m"    

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./homer_config:/www/assets:Z # Make sure your local config directory exists
    ports:
      - 8080:8080
    user: 1001:1001 # default
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped

  ocs-web-1:
    image: simonsobs/ocs-web:latest
    ports:
      - 8082:80
    volumes:
      - ./ocs-web/config.json:/app/dist/config.json:ro
    networks:
      - default
      - ocs-network
