# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
default_2fa_method: #totp

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
    client_certificates: []
  headers:
    csp_template: ""
  endpoints:
    authz:
      auth-request:
        implementation: 'AuthRequest'

log:
  level: debug

totp:
  disable: false
  issuer: alphadm.wlab.yale.edu
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m

  ldap:
    address: 'ldap://lldap:3890'
    implementation: 'lldap'
    timeout: '5s'
    start_tls: false
    base_dn: 'dc=alphadm,DC=edu'
    additional_users_dn: 'OU=people'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: 'OU=groups'
    groups_filter: '(member={dn})'
    user: 'UID=admin,OU=people,DC=alphadm,DC=edu'
    password: 'admin12345'
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'uid'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'

access_control:
  rules:
    - domain: '*.alphadm.wlab.yale.edu'
      subject: 
        - ['group:lldap_admin']
        - ['group:abc']
      policy: two_factor
    - domain: 'alphadm.wlab.yale.edu'
      subject: 
        - ['group:lldap_admin']
        - ['group:abc']
      policy: two_factor

session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  cookies:
    - domain: 'alphadm.wlab.yale.edu'
      authelia_url: 'https://auth.alphadm.wlab.yale.edu'
      #authelia_url: 'https://alphadm.wlab.yale.edu/authtest'
      default_redirection_url: 'https://alphadm.wlab.yale.edu'
      
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: 'dee329bf-63a1-49a6-8278-c088e2de681e'
  postgres:
    address: 'tcp://db:5432'
    database: 'general'
    schema: 'authelia'
    username: 'authelia_user'
    password: 'authelia_password'
    timeout: '5s'

notifier:
  #filesystem:
  #  filename: /config/notification.txt

  smtp:
      address: 'smtp://mail.yale.edu'
      timeout: '5s'
      #username: 'test'
      #password: 'password'
      sender: "Authelia <sm3723@alphadm.stdusr.yale.internal>"
      identifier: 'alphadm'
      subject: "[Authelia] {title}"
      startup_check_address: 'seraphim.mcgann@yale.edu'
      disable_require_tls: false
      disable_starttls: false
      disable_html_emails: false
      #tls:
      #  server_name: 'smtp.example.com'
      #  skip_verify: false
      #  minimum_version: 'TLS1.2'
      #  maximum_version: 'TLS1.3'
      #  certificate_chain: |
      #    -----BEGIN CERTIFICATE-----
      #    ...
      #    -----END CERTIFICATE-----
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #    -----END CERTIFICATE-----
      #  private_key: |
      #    -----BEGIN PRIVATE KEY-----
      #    ...
      #    -----END PRIVATE KEY-----